# This is a basic workflow to help you get started with Actions

name: Test and Deploy a Microservice

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MATHWORKS_SKIP_ACTIVATION: true
  MATHWORKS_ACCOUNT: ${{secrets.MATHWORKS_ACCOUNT}}
  MATHWORKS_TOKEN: ${{secrets.MATHWORKS_TOKEN}}
  
jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3 
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023b

#TODO:uncomment and complete these steps to run tests and upload artifacts
      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1
          
      - name: Upload the artifacts to GitHub
        if: always()
      - uses: actions/checkout@v3

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
        

        
  build-and-deploy:
    needs: run-test
    runs-on: ubuntu-latest
  
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3 
        
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: R2023b
      
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        
      - name: Create the microservice
        if: success()
        uses: matlab-actions/run-command@v1
        with:
          command: buildMicroservice
      
      - name: Connect to Azure registry
        uses: azure/docker-login@v1
        with:
          login-server: olarssoncloudtraining.azurecr.io #TODO: Change to match the name of your container registry
          username:  ${{ secrets.REGISTRY_USERNAME }}
          password:  ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Tag and push the Docker image to Azure
        run: |
          docker tag my-microservice olarssoncloudtraining.azurecr.io/my-microservice:latest #TODO: Change to match the name of your container registry
          docker push  olarssoncloudtraining.azurecr.io/my-microservice:latest #TODO: Change to match the name of your container registry
